version: '2'
services:
  app:
    image: clientside_aws_test_app
    container_name: clientside_aws_test_app
    links:
      - aws
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      /sbin/my_init
    ports:
      - '4567'
  aws:
    image: clientside_aws:latest
    container_name: clientside_aws_test_aws
    build:
      context: ../../
      dockerfile: ./Dockerfile
    command: /sbin/my_init
    ports:
      - '4567'
